const studentSchema = {
    first: '',
    middle: '',
    last: '',
    nickname: '',
    year: '',
    major: [],
    minor: [],
    portfolioLink: '',
    pronouns: '',
    resume: '',
    softskills: '',
    bio: '',
    image: '',
}
